/**
 * Employee TypeScript Types
 * Generated by smartadmin-react-crud skill
 * Backend alignment: net.lab1024.sa.system.employee.domain.*
 */

/**
 * Employee Query Form
 * Backend: net.lab1024.sa.system.employee.domain.form.EmployeeQueryForm
 */
export interface EmployeeQueryForm {
  keyword?: string;              // Search keyword
  pageNum: number;               // Page number
  pageSize: number;              // Page size
  departmentId?: number;         // Department ID (optional filter)
  status?: 1 | 2 | 3;           // Status filter (optional)
  createTimeStart?: string;      // Create time range start (optional)
  createTimeEnd?: string;        // Create time range end (optional)
}

/**
 * Employee VO (View Object)
 * Backend: net.lab1024.sa.system.employee.domain.vo.EmployeeVO
 */
export interface EmployeeVO {
  employeeId: number;            // Primary key (Long -> number)
  employeeName: string;          // Employee name
  email: string;                 // Email address
  phone?: string;                // Phone number (optional)
  departmentId: number;          // Department ID
  departmentName?: string;       // Department name (JOIN field)
  position: string;              // Position/Title
  status: 1 | 2 | 3;            // Status: 1=Active, 2=Resigned, 3=Disabled
  salary?: number;               // Salary (optional)
  entryDate?: string;            // Entry date (ISO 8601, optional)
  createTime: string;            // Create time (ISO 8601)
  updateTime: string;            // Update time (ISO 8601)
  deleted: boolean;              // Soft delete flag
}

/**
 * Employee Add Form
 * Backend: net.lab1024.sa.system.employee.domain.form.EmployeeAddForm
 */
export interface EmployeeAddForm {
  employeeName: string;          // Employee name (required, @NotBlank)
  email: string;                 // Email (required, @NotBlank)
  phone?: string;                // Phone number (optional)
  departmentId: number;          // Department ID (required, @NotNull)
  position: string;              // Position (required, @NotBlank)
  status: 1 | 2 | 3;            // Status (required)
  salary?: number;               // Salary (optional)
  entryDate?: string;            // Entry date (optional)
}

/**
 * Employee Update Form
 * Backend: net.lab1024.sa.system.employee.domain.form.EmployeeUpdateForm
 */
export interface EmployeeUpdateForm {
  employeeId: number;            // Primary key (required)
  employeeName: string;          // Employee name (required)
  email: string;                 // Email (required)
  phone?: string;                // Phone number (optional)
  departmentId: number;          // Department ID (required)
  position: string;              // Position (required)
  status: 1 | 2 | 3;            // Status (required)
  salary?: number;               // Salary (optional)
  entryDate?: string;            // Entry date (optional)
}

/**
 * Employee Batch Delete Form
 */
export interface EmployeeBatchDeleteForm {
  employeeIdList: number[];      // ID list for batch deletion
}

/**
 * Employee Status Enum
 * Usage: <Select.Option value={EmployeeStatusEnum.ACTIVE.value}>
 *          {EmployeeStatusEnum.ACTIVE.label}
 *        </Select.Option>
 */
export const EmployeeStatusEnum = {
  ACTIVE: { value: 1, label: '在職' },
  RESIGNED: { value: 2, label: '離職' },
  DISABLED: { value: 3, label: '禁用' },
} as const;

/**
 * Employee Status Type (extracted from enum values)
 */
export type EmployeeStatus = typeof EmployeeStatusEnum[keyof typeof EmployeeStatusEnum]['value'];
