/**
 * Employee API Client
 * Generated by smartadmin-react-crud skill
 * Backend Controller: net.lab1024.sa.system.employee.controller.EmployeeController
 */

import { postRequest, getRequest } from '@/api/base/request';
import type { PageResult } from '@/api/base/response.model';
import type {
  EmployeeQueryForm,
  EmployeeVO,
  EmployeeAddForm,
  EmployeeUpdateForm,
  EmployeeBatchDeleteForm,
} from './employee-types';

const BASE_URL = '/system/employee';

/**
 * Employee API Methods
 */
export const employeeApi = {
  /**
   * Paginated query
   * Backend: POST /system/employee/query
   */
  query: (queryForm: EmployeeQueryForm) => {
    return postRequest<PageResult<EmployeeVO>>(`${BASE_URL}/query`, queryForm);
  },

  /**
   * Get employee by ID
   * Backend: GET /system/employee/get/{employeeId}
   */
  getById: (employeeId: number) => {
    return getRequest<EmployeeVO>(`${BASE_URL}/get/${employeeId}`);
  },

  /**
   * Add new employee
   * Backend: POST /system/employee/add
   * Permission: system:employee:add
   */
  add: (addForm: EmployeeAddForm) => {
    return postRequest<void>(`${BASE_URL}/add`, addForm);
  },

  /**
   * Update existing employee
   * Backend: POST /system/employee/update
   * Permission: system:employee:update
   */
  update: (updateForm: EmployeeUpdateForm) => {
    return postRequest<void>(`${BASE_URL}/update`, updateForm);
  },

  /**
   * Delete employee by ID
   * Backend: POST /system/employee/delete/{employeeId}
   * Permission: system:employee:delete
   */
  delete: (employeeId: number) => {
    return postRequest<void>(`${BASE_URL}/delete/${employeeId}`);
  },

  /**
   * Batch delete employees
   * Backend: POST /system/employee/batchDelete
   * Permission: system:employee:delete
   */
  batchDelete: (batchDeleteForm: EmployeeBatchDeleteForm) => {
    return postRequest<void>(`${BASE_URL}/batchDelete`, batchDeleteForm);
  },
};
