/**
 * Employee Form Modal Component
 * Generated by smartadmin-react-crud skill
 */

import React, { useEffect } from 'react';
import { Modal, Form, Input, message, Select, InputNumber } from 'antd';
import { employeeApi } from '@/api/system/employee-api';
import type {
  EmployeeVO,
  EmployeeAddForm,
  EmployeeUpdateForm,
} from '@/api/system/employee-types';
import { EmployeeStatusEnum } from '@/api/system/employee-types';

interface EmployeeFormModalProps {
  visible: boolean;
  record: EmployeeVO | null;
  onCancel: () => void;
  onSuccess: () => void;
}

/**
 * Employee Form Modal (Add/Edit Mode)
 */
export const EmployeeFormModal: React.FC<EmployeeFormModalProps> = ({
  visible,
  record,
  onCancel,
  onSuccess,
}) => {
  const [form] = Form.useForm();
  const [loading, setLoading] = React.useState(false);
  const isEdit = record !== null;

  // ===== Form Initialization =====
  useEffect(() => {
    if (visible && record) {
      // Edit mode: fill form with existing data
      form.setFieldsValue(record);
    } else if (visible) {
      // Add mode: reset form
      form.resetFields();
    }
  }, [visible, record, form]);

  // ===== Form Submission =====
  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      setLoading(true);

      const response = isEdit
        ? await employeeApi.update({
            ...values,
            employeeId: record.employeeId,
          } as EmployeeUpdateForm)
        : await employeeApi.add(values as EmployeeAddForm);

      if (response.success) {
        message.success(isEdit ? '更新成功' : '添加成功');
        onSuccess();
      } else {
        message.error(response.msg || (isEdit ? '更新失敗' : '添加失敗'));
      }
    } catch (error) {
      // Validation failed or API error
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Modal
      title={isEdit ? '編輯員工' : '新增員工'}
      open={visible}
      onOk={handleSubmit}
      onCancel={onCancel}
      confirmLoading={loading}
      width={600}
      destroyOnClose
    >
      <Form
        form={form}
        labelCol={{ span: 6 }}
        wrapperCol={{ span: 16 }}
        autoComplete="off"
      >
        {/* Employee Name */}
        <Form.Item
          label="姓名"
          name="employeeName"
          rules={[
            { required: true, message: '請輸入姓名' },
            { min: 2, max: 50, message: '長度為 2-50 個字符' },
          ]}
        >
          <Input placeholder="請輸入姓名" />
        </Form.Item>

        {/* Email */}
        <Form.Item
          label="郵箱"
          name="email"
          rules={[
            { required: true, message: '請輸入郵箱' },
            { type: 'email', message: '郵箱格式不正確' },
          ]}
        >
          <Input placeholder="請輸入郵箱" />
        </Form.Item>

        {/* Phone */}
        <Form.Item
          label="電話"
          name="phone"
          rules={[
            { pattern: /^1[3-9]\d{9}$/, message: '手機號碼格式不正確' },
          ]}
        >
          <Input placeholder="請輸入電話" />
        </Form.Item>

        {/* Department */}
        <Form.Item
          label="部門"
          name="departmentId"
          rules={[{ required: true, message: '請選擇部門' }]}
        >
          <Select placeholder="請選擇部門">
            <Select.Option value={1}>技術部</Select.Option>
            <Select.Option value={2}>產品部</Select.Option>
            <Select.Option value={3}>運營部</Select.Option>
            <Select.Option value={4}>人力資源部</Select.Option>
            <Select.Option value={5}>財務部</Select.Option>
          </Select>
        </Form.Item>

        {/* Position */}
        <Form.Item
          label="職位"
          name="position"
          rules={[
            { required: true, message: '請輸入職位' },
            { min: 2, max: 30, message: '長度為 2-30 個字符' },
          ]}
        >
          <Input placeholder="請輸入職位" />
        </Form.Item>

        {/* Status */}
        <Form.Item
          label="狀態"
          name="status"
          rules={[{ required: true, message: '請選擇狀態' }]}
          initialValue={1}
        >
          <Select placeholder="請選擇狀態">
            <Select.Option value={EmployeeStatusEnum.ACTIVE.value}>
              {EmployeeStatusEnum.ACTIVE.label}
            </Select.Option>
            <Select.Option value={EmployeeStatusEnum.RESIGNED.value}>
              {EmployeeStatusEnum.RESIGNED.label}
            </Select.Option>
            <Select.Option value={EmployeeStatusEnum.DISABLED.value}>
              {EmployeeStatusEnum.DISABLED.label}
            </Select.Option>
          </Select>
        </Form.Item>

        {/* Salary */}
        <Form.Item label="薪資" name="salary">
          <InputNumber
            min={0}
            max={1000000}
            precision={2}
            style={{ width: '100%' }}
            placeholder="請輸入薪資"
          />
        </Form.Item>

        {/* Entry Date */}
        <Form.Item label="入職日期" name="entryDate">
          <Input type="date" placeholder="請選擇入職日期" />
        </Form.Item>
      </Form>
    </Modal>
  );
};
