/**
 * Employee List Component
 * Generated by smartadmin-react-crud skill
 */

import React, { useState, useEffect } from 'react';
import { Table, Button, message, Form, Input, Space, Modal } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { PlusOutlined, DeleteOutlined } from '@ant-design/icons';
import { PrivilegeButton } from '@/components/framework/privilege/PrivilegeButton';
import { employeeApi } from '@/api/system/employee-api';
import type { EmployeeVO, EmployeeQueryForm } from '@/api/system/employee-types';
import { EmployeeStatusEnum } from '@/api/system/employee-types';
import { EmployeeFormModal } from './EmployeeFormModal';

/**
 * Employee List Page
 */
export const EmployeeList: React.FC = () => {
  // ===== State Management =====
  const [data, setData] = useState<EmployeeVO[]>([]);
  const [loading, setLoading] = useState(false);
  const [total, setTotal] = useState(0);
  const [queryForm, setQueryForm] = useState<EmployeeQueryForm>({
    pageNum: 1,
    pageSize: 10,
    keyword: '',
  });
  const [selectedRowKeys, setSelectedRowKeys] = useState<React.Key[]>([]);
  const [formModalVisible, setFormModalVisible] = useState(false);
  const [currentRecord, setCurrentRecord] = useState<EmployeeVO | null>(null);

  // ===== Data Fetching =====
  const fetchData = async () => {
    setLoading(true);
    try {
      const response = await employeeApi.query(queryForm);
      if (response.success) {
        setData(response.data.list);
        setTotal(response.data.total);
      } else {
        message.error(response.msg || '查詢失敗');
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [queryForm]);

  // ===== Event Handlers =====
  const handleAdd = () => {
    setCurrentRecord(null);
    setFormModalVisible(true);
  };

  const handleEdit = (record: EmployeeVO) => {
    setCurrentRecord(record);
    setFormModalVisible(true);
  };

  const handleDelete = (record: EmployeeVO) => {
    Modal.confirm({
      title: '確認刪除',
      content: `確定要刪除員工「${record.employeeName}」嗎？`,
      onOk: async () => {
        const response = await employeeApi.delete(record.employeeId);
        if (response.success) {
          message.success('刪除成功');
          fetchData();
        } else {
          message.error(response.msg || '刪除失敗');
        }
      },
    });
  };

  const handleBatchDelete = () => {
    if (selectedRowKeys.length === 0) {
      message.warning('請選擇要刪除的記錄');
      return;
    }

    Modal.confirm({
      title: '批量刪除確認',
      content: `確定要刪除選中的 ${selectedRowKeys.length} 條記錄嗎？`,
      onOk: async () => {
        const response = await employeeApi.batchDelete({
          employeeIdList: selectedRowKeys as number[],
        });
        if (response.success) {
          message.success('批量刪除成功');
          setSelectedRowKeys([]);
          fetchData();
        } else {
          message.error(response.msg || '批量刪除失敗');
        }
      },
    });
  };

  const handleSearch = () => {
    setQueryForm({ ...queryForm, pageNum: 1 });
  };

  const handleReset = () => {
    setQueryForm({ pageNum: 1, pageSize: 10, keyword: '' });
  };

  // ===== Table Columns =====
  const columns: ColumnsType<EmployeeVO> = [
    {
      title: 'ID',
      dataIndex: 'employeeId',
      key: 'employeeId',
      width: 80,
      fixed: 'left',
    },
    {
      title: '姓名',
      dataIndex: 'employeeName',
      key: 'employeeName',
      width: 120,
    },
    {
      title: '郵箱',
      dataIndex: 'email',
      key: 'email',
      width: 200,
    },
    {
      title: '電話',
      dataIndex: 'phone',
      key: 'phone',
      width: 120,
    },
    {
      title: '部門',
      dataIndex: 'departmentName',
      key: 'departmentName',
      width: 120,
    },
    {
      title: '職位',
      dataIndex: 'position',
      key: 'position',
      width: 120,
    },
    {
      title: '狀態',
      dataIndex: 'status',
      key: 'status',
      width: 100,
      render: (status: 1 | 2 | 3) => {
        const statusConfig = Object.values(EmployeeStatusEnum).find(
          (item) => item.value === status
        );
        return statusConfig?.label || '未知';
      },
    },
    {
      title: '創建時間',
      dataIndex: 'createTime',
      key: 'createTime',
      width: 180,
    },
    {
      title: '操作',
      key: 'action',
      width: 150,
      fixed: 'right',
      render: (_: unknown, record: EmployeeVO) => (
        <Space>
          <PrivilegeButton
            permissionCode="system:employee:update"
            type="link"
            size="small"
            onClick={() => handleEdit(record)}
          >
            編輯
          </PrivilegeButton>
          <PrivilegeButton
            permissionCode="system:employee:delete"
            type="link"
            size="small"
            danger
            onClick={() => handleDelete(record)}
          >
            刪除
          </PrivilegeButton>
        </Space>
      ),
    },
  ];

  // ===== Render =====
  return (
    <div style={{ padding: 24 }}>
      {/* Search Form */}
      <Form layout="inline" style={{ marginBottom: 16 }}>
        <Form.Item label="關鍵字">
          <Input
            placeholder="請輸入搜索關鍵字"
            value={queryForm.keyword}
            onChange={(e) =>
              setQueryForm({ ...queryForm, keyword: e.target.value })
            }
            onPressEnter={handleSearch}
            style={{ width: 200 }}
          />
        </Form.Item>
        <Form.Item>
          <Button type="primary" onClick={handleSearch}>
            查詢
          </Button>
          <Button onClick={handleReset} style={{ marginLeft: 8 }}>
            重置
          </Button>
        </Form.Item>
      </Form>

      {/* Action Buttons */}
      <Space style={{ marginBottom: 16 }}>
        <PrivilegeButton
          permissionCode="system:employee:add"
          type="primary"
          icon={<PlusOutlined />}
          onClick={handleAdd}
        >
          新增員工
        </PrivilegeButton>
        <PrivilegeButton
          permissionCode="system:employee:delete"
          danger
          icon={<DeleteOutlined />}
          disabled={selectedRowKeys.length === 0}
          onClick={handleBatchDelete}
        >
          批量刪除
        </PrivilegeButton>
      </Space>

      {/* Data Table */}
      <Table
        dataSource={data}
        columns={columns}
        loading={loading}
        rowKey="employeeId"
        rowSelection={{
          selectedRowKeys,
          onChange: setSelectedRowKeys,
        }}
        pagination={{
          current: queryForm.pageNum,
          pageSize: queryForm.pageSize,
          total: total,
          showSizeChanger: true,
          showQuickJumper: true,
          showTotal: (total) => `共 ${total} 條`,
          onChange: (pageNum, pageSize) =>
            setQueryForm({ ...queryForm, pageNum, pageSize }),
        }}
        scroll={{ x: 1200 }}
      />

      {/* Form Modal */}
      <EmployeeFormModal
        visible={formModalVisible}
        record={currentRecord}
        onCancel={() => setFormModalVisible(false)}
        onSuccess={() => {
          setFormModalVisible(false);
          fetchData();
        }}
      />
    </div>
  );
};
