#!/bin/bash
# Pre-commit Quality Gate Hook
# Location: .git/hooks/pre-commit
# Generated by: quality-gate-orchestrator skill

set -e

echo "======================================"
echo "🔍 Running Pre-Commit Quality Checks"
echo "======================================"
echo ""

START_TIME=$(date +%s)

# Navigate to project directory
cd "$(git rev-parse --show-toplevel)/smart-admin-api-java21-springboot3"

# Function to print colored output
print_status() {
    if [ $1 -eq 0 ]; then
        echo "✅ $2"
    else
        echo "❌ $2"
    fi
}

# Function to print duration
print_duration() {
    DURATION=$(($(date +%s) - $1))
    echo "   Duration: ${DURATION}s"
}

# Step 1: Auto-format (always run, non-blocking)
echo "1️⃣  Running Spotless (auto-format)..."
STEP_START=$(date +%s)
./gradlew spotlessApply --quiet --no-daemon || true
print_status 0 "Code formatting complete"
print_duration $STEP_START
echo ""

# Step 2: Checkstyle (BLOCKER)
echo "2️⃣  Running Checkstyle (code style)..."
STEP_START=$(date +%s)
if ./gradlew :sa-admin:checkstyleMain --quiet --no-daemon; then
    print_status 0 "Checkstyle passed"
    print_duration $STEP_START
    echo ""
else
    print_status 1 "Checkstyle failed"
    print_duration $STEP_START
    echo ""
    echo "⚠️  Fix Checkstyle violations before committing."
    echo "   View report: sa-admin/build/reports/checkstyle/main.html"
    echo ""
    exit 1
fi

# Step 3: ArchUnit (BLOCKER - critical architecture rules only)
echo "3️⃣  Running ArchUnit (architecture rules)..."
STEP_START=$(date +%s)
if ./gradlew :sa-admin:test --tests "*ArchitectureTest" --quiet --no-daemon; then
    print_status 0 "ArchUnit tests passed"
    print_duration $STEP_START
    echo ""
else
    print_status 1 "ArchUnit tests failed"
    print_duration $STEP_START
    echo ""
    echo "⚠️  Fix architecture violations before committing."
    echo "   View report: sa-admin/build/reports/tests/test/index.html"
    echo ""
    exit 1
fi

# Optional: Quick PMD check (only changed files)
if command -v pmd &> /dev/null; then
    echo "4️⃣  Running PMD (changed files only)..."
    STEP_START=$(date +%s)
    CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.java$' || true)

    if [ -n "$CHANGED_FILES" ]; then
        if pmd check -d $CHANGED_FILES -R config/pmd/ruleset.xml --format text --no-cache --quiet; then
            print_status 0 "PMD check passed"
        else
            print_status 1 "PMD check failed (non-blocking)"
            echo "   ⚠️  Consider fixing PMD violations"
        fi
        print_duration $STEP_START
        echo ""
    else
        echo "   ⏭️  No Java files changed, skipping PMD"
        echo ""
    fi
fi

# Success summary
END_TIME=$(date +%s)
TOTAL_DURATION=$((END_TIME - START_TIME))

echo "======================================"
echo "✅ Pre-Commit Checks Passed"
echo "======================================"
echo ""
echo "Total duration: ${TOTAL_DURATION}s"
echo ""
echo "Proceeding with commit..."
echo "======================================"

exit 0
