// Quality Gate - Sequential Execution (Fail-Fast)
// Location: smart-admin-api-java21-springboot3/build.gradle.kts
// Generated by: quality-gate-orchestrator skill

tasks.register("qualityGateSequential") {
    description = "Run quality checks sequentially with fail-fast strategy"
    group = "verification"

    doLast {
        println("=" .repeat(80))
        println("🔍 SmartAdmin Quality Gate - Sequential Validation")
        println("=" .repeat(80))
        println()

        val startTime = System.currentTimeMillis()
        val results = mutableMapOf<String, Pair<Int, Long>>()

        // Step 1: Auto-format (always run first, non-blocking)
        println("1️⃣  Running Spotless (auto-format)...")
        val spotlessStart = System.currentTimeMillis()
        try {
            exec {
                workingDir = file("smart-admin-api-java21-springboot3")
                commandLine("./gradlew", "spotlessApply", "--no-daemon")
            }
            val spotlessDuration = System.currentTimeMillis() - spotlessStart
            results["Spotless"] = 0 to spotlessDuration
            println("   ✅ Code formatting complete (${spotlessDuration}ms)")
        } catch (e: Exception) {
            val spotlessDuration = System.currentTimeMillis() - spotlessStart
            results["Spotless"] = 1 to spotlessDuration
            println("   ⚠️  Spotless failed (${spotlessDuration}ms) - continuing...")
        }
        println()

        // Step 2: Checkstyle (BLOCKER - fail immediately)
        println("2️⃣  Running Checkstyle (code style)...")
        val checkstyleStart = System.currentTimeMillis()
        try {
            exec {
                workingDir = file("smart-admin-api-java21-springboot3")
                commandLine("./gradlew", ":sa-admin:checkstyleMain", ":sa-admin:checkstyleTest", "--no-daemon")
                isIgnoreExitValue = false
            }
            val checkstyleDuration = System.currentTimeMillis() - checkstyleStart
            results["Checkstyle"] = 0 to checkstyleDuration
            println("   ✅ Checkstyle: 0 violations (${checkstyleDuration}ms)")
        } catch (e: Exception) {
            val checkstyleDuration = System.currentTimeMillis() - checkstyleStart
            results["Checkstyle"] = 1 to checkstyleDuration
            println("   ❌ Checkstyle violations detected (${checkstyleDuration}ms)")
            println()
            printFailureSummary(results, startTime, "Checkstyle", 2, 6)
            throw GradleException("Quality gate FAILED at Checkstyle (BLOCKER)")
        }
        println()

        // Step 3: ArchUnit (BLOCKER - architecture rules)
        println("3️⃣  Running ArchUnit (architecture rules)...")
        val archunitStart = System.currentTimeMillis()
        try {
            exec {
                workingDir = file("smart-admin-api-java21-springboot3")
                commandLine("./gradlew", ":sa-admin:test", "--tests", "*ArchitectureTest", "--no-daemon")
                isIgnoreExitValue = false
            }
            val archunitDuration = System.currentTimeMillis() - archunitStart
            results["ArchUnit"] = 0 to archunitDuration
            println("   ✅ ArchUnit: All architecture rules passed (${archunitDuration}ms)")
        } catch (e: Exception) {
            val archunitDuration = System.currentTimeMillis() - archunitStart
            results["ArchUnit"] = 1 to archunitDuration
            println("   ❌ ArchUnit violations detected (${archunitDuration}ms)")
            println()
            printFailureSummary(results, startTime, "ArchUnit", 3, 6)
            throw GradleException("Quality gate FAILED at ArchUnit (BLOCKER)")
        }
        println()

        // Step 4: PMD (CRITICAL - code smells)
        println("4️⃣  Running PMD (code quality)...")
        val pmdStart = System.currentTimeMillis()
        try {
            exec {
                workingDir = file("smart-admin-api-java21-springboot3")
                commandLine("./gradlew", ":sa-admin:pmdMain", "--no-daemon")
                isIgnoreExitValue = false
            }
            val pmdDuration = System.currentTimeMillis() - pmdStart
            results["PMD"] = 0 to pmdDuration
            println("   ✅ PMD: 0 violations (${pmdDuration}ms)")
        } catch (e: Exception) {
            val pmdDuration = System.currentTimeMillis() - pmdStart
            results["PMD"] = 1 to pmdDuration
            println("   ❌ PMD violations detected (${pmdDuration}ms)")
            println()
            printFailureSummary(results, startTime, "PMD", 4, 6)
            throw GradleException("Quality gate FAILED at PMD (CRITICAL)")
        }
        println()

        // Step 5: SpotBugs (CRITICAL - bug patterns)
        println("5️⃣  Running SpotBugs (bug detection)...")
        val spotbugsStart = System.currentTimeMillis()
        try {
            exec {
                workingDir = file("smart-admin-api-java21-springboot3")
                commandLine("./gradlew", ":sa-admin:spotbugsMain", "--no-daemon")
                isIgnoreExitValue = false
            }
            val spotbugsDuration = System.currentTimeMillis() - spotbugsStart
            results["SpotBugs"] = 0 to spotbugsDuration
            println("   ✅ SpotBugs: 0 bugs detected (${spotbugsDuration}ms)")
        } catch (e: Exception) {
            val spotbugsDuration = System.currentTimeMillis() - spotbugsStart
            results["SpotBugs"] = 1 to spotbugsDuration
            println("   ❌ SpotBugs violations detected (${spotbugsDuration}ms)")
            println()
            printFailureSummary(results, startTime, "SpotBugs", 5, 6)
            throw GradleException("Quality gate FAILED at SpotBugs (CRITICAL)")
        }
        println()

        // Step 6: JaCoCo Coverage Verification (MAJOR - coverage threshold)
        println("6️⃣  Running JaCoCo (coverage verification)...")
        val jacocoStart = System.currentTimeMillis()
        try {
            exec {
                workingDir = file("smart-admin-api-java21-springboot3")
                commandLine("./gradlew", ":sa-admin:test", ":sa-admin:jacocoTestReport", ":sa-admin:jacocoTestCoverageVerification", "--no-daemon")
                isIgnoreExitValue = false
            }
            val jacocoDuration = System.currentTimeMillis() - jacocoStart
            results["JaCoCo"] = 0 to jacocoDuration
            println("   ✅ JaCoCo: Coverage threshold met (≥80%) (${jacocoDuration}ms)")
        } catch (e: Exception) {
            val jacocoDuration = System.currentTimeMillis() - jacocoStart
            results["JaCoCo"] = 1 to jacocoDuration
            println("   ❌ JaCoCo: Coverage below threshold (${jacocoDuration}ms)")
            println()
            printFailureSummary(results, startTime, "JaCoCo", 6, 6)
            throw GradleException("Quality gate FAILED at JaCoCo (MAJOR)")
        }
        println()

        // Success summary
        printSuccessSummary(results, startTime)
    }
}

fun printFailureSummary(
    results: Map<String, Pair<Int, Long>>,
    startTime: Long,
    failedTool: String,
    failedStep: Int,
    totalSteps: Int
) {
    println("=" .repeat(80))
    println("❌ Quality Gate FAILED")
    println("=" .repeat(80))
    println()
    println("Failed at: Step $failedStep/$totalSteps - $failedTool")
    println("Total execution time: ${System.currentTimeMillis() - startTime}ms")
    println()
    println("Completed steps:")
    results.forEach { (tool, result) ->
        val (exitCode, duration) = result
        val status = if (exitCode == 0) "✅" else "❌"
        println("  $status $tool (${duration}ms)")
    }
    println()
    println("View detailed reports:")
    println("  - Checkstyle: sa-admin/build/reports/checkstyle/main.html")
    println("  - PMD: sa-admin/build/reports/pmd/main.html")
    println("  - SpotBugs: sa-admin/build/reports/spotbugs/main.html")
    println("  - Tests: sa-admin/build/reports/tests/test/index.html")
    println("  - Coverage: sa-admin/build/reports/jacoco/test/html/index.html")
    println("=" .repeat(80))
}

fun printSuccessSummary(results: Map<String, Pair<Int, Long>>, startTime: Long) {
    val totalDuration = System.currentTimeMillis() - startTime
    println("=" .repeat(80))
    println("✅ Quality Gate PASSED")
    println("=" .repeat(80))
    println()
    println("All quality checks completed successfully!")
    println()
    println("Execution breakdown:")
    results.forEach { (tool, result) ->
        val (_, duration) = result
        val percentage = (duration.toDouble() / totalDuration * 100).toInt()
        println("  ✅ $tool: ${duration}ms ($percentage%)")
    }
    println()
    println("Total execution time: ${totalDuration}ms")
    println()
    println("Quality reports available at:")
    println("  - Checkstyle: sa-admin/build/reports/checkstyle/main.html")
    println("  - PMD: sa-admin/build/reports/pmd/main.html")
    println("  - SpotBugs: sa-admin/build/reports/spotbugs/main.html")
    println("  - Tests: sa-admin/build/reports/tests/test/index.html")
    println("  - Coverage: sa-admin/build/reports/jacoco/test/html/index.html")
    println("=" .repeat(80))
}
