/**
 * EmployeeFormModal Component Tests
 * Generated by smartadmin-react-crud skill
 */

import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { vi } from 'vitest';
import { EmployeeFormModal } from '../EmployeeFormModal';
import { employeeApi } from '@/api/system/employee-api';

vi.mock('@/api/system/employee-api');

describe('EmployeeFormModal Component', () => {
  const mockOnCancel = vi.fn();
  const mockOnSuccess = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should render in add mode when record is null', () => {
    render(
      <EmployeeFormModal
        visible={true}
        record={null}
        onCancel={mockOnCancel}
        onSuccess={mockOnSuccess}
      />
    );

    expect(screen.getByText(/新增員工/i)).toBeInTheDocument();
  });

  it('should render in edit mode when record is provided', () => {
    const mockRecord = {
      employeeId: 1,
      employeeName: 'John Doe',
      email: 'john@example.com',
      phone: '13800138000',
      departmentId: 1,
      departmentName: '技術部',
      position: 'Developer',
      status: 1 as const,
      createTime: '2026-03-06T10:00:00Z',
      updateTime: '2026-03-06T10:00:00Z',
      deleted: false,
    };

    render(
      <EmployeeFormModal
        visible={true}
        record={mockRecord}
        onCancel={mockOnCancel}
        onSuccess={mockOnSuccess}
      />
    );

    expect(screen.getByText(/編輯員工/i)).toBeInTheDocument();
    expect(screen.getByDisplayValue('John Doe')).toBeInTheDocument();
    expect(screen.getByDisplayValue('john@example.com')).toBeInTheDocument();
  });

  it('should call add API when submitting in add mode', async () => {
    const user = userEvent.setup();
    vi.mocked(employeeApi.add).mockResolvedValue({ success: true });

    render(
      <EmployeeFormModal
        visible={true}
        record={null}
        onCancel={mockOnCancel}
        onSuccess={mockOnSuccess}
      />
    );

    // Fill form
    const nameInput = screen.getByLabelText('姓名');
    await user.type(nameInput, 'John Doe');

    const emailInput = screen.getByLabelText('郵箱');
    await user.type(emailInput, 'john@example.com');

    const positionInput = screen.getByLabelText('職位');
    await user.type(positionInput, 'Developer');

    // Submit form
    const okButton = screen.getByText('確定');
    await user.click(okButton);

    await waitFor(() => {
      expect(employeeApi.add).toHaveBeenCalledWith(
        expect.objectContaining({
          employeeName: 'John Doe',
          email: 'john@example.com',
          position: 'Developer',
        })
      );
      expect(mockOnSuccess).toHaveBeenCalled();
    }, { timeout: 5000 });
  });

  it('should call update API when submitting in edit mode', async () => {
    const user = userEvent.setup();
    const mockRecord = {
      employeeId: 1,
      employeeName: 'John Doe',
      email: 'john@example.com',
      phone: '13800138000',
      departmentId: 1,
      departmentName: '技術部',
      position: 'Developer',
      status: 1 as const,
      createTime: '2026-03-06T10:00:00Z',
      updateTime: '2026-03-06T10:00:00Z',
      deleted: false,
    };
    vi.mocked(employeeApi.update).mockResolvedValue({ success: true });

    render(
      <EmployeeFormModal
        visible={true}
        record={mockRecord}
        onCancel={mockOnCancel}
        onSuccess={mockOnSuccess}
      />
    );

    // Modify form
    const nameInput = screen.getByDisplayValue('John Doe');
    await user.clear(nameInput);
    await user.type(nameInput, 'Jane Doe');

    // Submit form
    const okButton = screen.getByText('確定');
    await user.click(okButton);

    await waitFor(() => {
      expect(employeeApi.update).toHaveBeenCalledWith(
        expect.objectContaining({
          employeeId: 1,
          employeeName: 'Jane Doe',
        })
      );
      expect(mockOnSuccess).toHaveBeenCalled();
    }, { timeout: 5000 });
  });

  it('should show validation errors for invalid form data', async () => {
    const user = userEvent.setup();

    render(
      <EmployeeFormModal
        visible={true}
        record={null}
        onCancel={mockOnCancel}
        onSuccess={mockOnSuccess}
      />
    );

    // Submit without filling required fields
    const okButton = screen.getByText('確定');
    await user.click(okButton);

    await waitFor(() => {
      expect(screen.getByText(/請輸入姓名/i)).toBeInTheDocument();
    }, { timeout: 5000 });

    expect(employeeApi.add).not.toHaveBeenCalled();
  });

  it('should validate email format', async () => {
    const user = userEvent.setup();

    render(
      <EmployeeFormModal
        visible={true}
        record={null}
        onCancel={mockOnCancel}
        onSuccess={mockOnSuccess}
      />
    );

    // Fill with invalid email
    const nameInput = screen.getByLabelText('姓名');
    await user.type(nameInput, 'John Doe');

    const emailInput = screen.getByLabelText('郵箱');
    await user.type(emailInput, 'invalid-email');

    const positionInput = screen.getByLabelText('職位');
    await user.type(positionInput, 'Developer');

    // Submit form
    const okButton = screen.getByText('確定');
    await user.click(okButton);

    await waitFor(() => {
      expect(screen.getByText(/郵箱格式不正確/i)).toBeInTheDocument();
    }, { timeout: 5000 });

    expect(employeeApi.add).not.toHaveBeenCalled();
  });
});
