/**
 * EmployeeFormModal Component Tests
 * Generated by smartadmin-react-crud skill
 */

import { render, screen, waitFor, fireEvent, act } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { vi } from 'vitest';
import { Form } from 'antd';
import type { FormInstance } from 'antd';
import { EmployeeFormModal } from '../EmployeeFormModal';
import { employeeApi } from '@/api/system/employee-api';

vi.mock('@/api/system/employee-api');

describe('EmployeeFormModal Component', () => {
  const mockOnCancel = vi.fn();
  const mockOnSuccess = vi.fn();

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should render in add mode when record is null', () => {
    render(
      <EmployeeFormModal
        visible={true}
        record={null}
        onCancel={mockOnCancel}
        onSuccess={mockOnSuccess}
      />
    );

    expect(screen.getByText(/新增員工/i)).toBeInTheDocument();
  });

  it('should render in edit mode when record is provided', () => {
    const mockRecord = {
      employeeId: 1,
      employeeName: 'John Doe',
      email: 'john@example.com',
      phone: '13800138000',
      departmentId: 1,
      departmentName: '技術部',
      position: 'Developer',
      status: 1 as const,
      createTime: '2026-03-06T10:00:00Z',
      updateTime: '2026-03-06T10:00:00Z',
      deleted: false,
    };

    render(
      <EmployeeFormModal
        visible={true}
        record={mockRecord}
        onCancel={mockOnCancel}
        onSuccess={mockOnSuccess}
      />
    );

    expect(screen.getByText(/編輯員工/i)).toBeInTheDocument();
    expect(screen.getByDisplayValue('John Doe')).toBeInTheDocument();
    expect(screen.getByDisplayValue('john@example.com')).toBeInTheDocument();
  });

  it('should call add API when submitting in add mode', async () => {
    vi.mocked(employeeApi.add).mockResolvedValue({ success: true });

    // Spy on Form.useForm to capture the form instance
    let formInstance: FormInstance | undefined;
    const origUseForm = Form.useForm;
    const useFormSpy = vi.spyOn(Form, 'useForm').mockImplementation(() => {
      const result = origUseForm();
      formInstance = result[0];
      return result;
    });

    render(
      <EmployeeFormModal
        visible={true}
        record={null}
        onCancel={mockOnCancel}
        onSuccess={mockOnSuccess}
      />
    );

    // Fill text inputs with fireEvent.change
    fireEvent.change(screen.getByLabelText('姓名'), { target: { value: 'John Doe' } });
    fireEvent.change(screen.getByLabelText('郵箱'), { target: { value: 'john@example.com' } });
    fireEvent.change(screen.getByLabelText('職位'), { target: { value: 'Developer' } });

    // Set Select values programmatically (JSDOM can't render Ant Design Select CSS classes)
    await act(async () => {
      formInstance!.setFieldValue('departmentId', 1);
    });

    // Submit form
    fireEvent.click(screen.getByRole('button', { name: 'OK' }));

    await waitFor(() => {
      expect(employeeApi.add).toHaveBeenCalledWith(
        expect.objectContaining({
          employeeName: 'John Doe',
          email: 'john@example.com',
          position: 'Developer',
        })
      );
      expect(mockOnSuccess).toHaveBeenCalled();
    }, { timeout: 5000 });

    useFormSpy.mockRestore();
  });

  it('should call update API when submitting in edit mode', async () => {
    const mockRecord = {
      employeeId: 1,
      employeeName: 'John Doe',
      email: 'john@example.com',
      phone: '13800138000',
      departmentId: 1,
      departmentName: '技術部',
      position: 'Developer',
      status: 1 as const,
      createTime: '2026-03-06T10:00:00Z',
      updateTime: '2026-03-06T10:00:00Z',
      deleted: false,
    };
    vi.mocked(employeeApi.update).mockResolvedValue({ success: true });

    render(
      <EmployeeFormModal
        visible={true}
        record={mockRecord}
        onCancel={mockOnCancel}
        onSuccess={mockOnSuccess}
      />
    );

    // Modify form (use fireEvent.change for speed)
    const nameInput = screen.getByDisplayValue('John Doe');
    fireEvent.change(nameInput, { target: { value: 'Jane Doe' } });

    // Submit form
    fireEvent.click(screen.getByRole('button', { name: 'OK' }));

    await waitFor(() => {
      expect(employeeApi.update).toHaveBeenCalledWith(
        expect.objectContaining({
          employeeId: 1,
          employeeName: 'Jane Doe',
        })
      );
      expect(mockOnSuccess).toHaveBeenCalled();
    }, { timeout: 5000 });
  });

  it('should show validation errors for invalid form data', async () => {
    render(
      <EmployeeFormModal
        visible={true}
        record={null}
        onCancel={mockOnCancel}
        onSuccess={mockOnSuccess}
      />
    );

    // Submit without filling required fields (use fireEvent for speed)
    fireEvent.click(screen.getByRole('button', { name: 'OK' }));

    await waitFor(() => {
      expect(screen.getByText(/請輸入姓名/i)).toBeInTheDocument();
    }, { timeout: 5000 });

    expect(employeeApi.add).not.toHaveBeenCalled();
  });

  it('should validate email format', async () => {
    render(
      <EmployeeFormModal
        visible={true}
        record={null}
        onCancel={mockOnCancel}
        onSuccess={mockOnSuccess}
      />
    );

    // Fill with invalid email (use fireEvent.change for speed)
    fireEvent.change(screen.getByLabelText('姓名'), { target: { value: 'John Doe' } });
    fireEvent.change(screen.getByLabelText('郵箱'), { target: { value: 'invalid-email' } });
    fireEvent.change(screen.getByLabelText('職位'), { target: { value: 'Developer' } });

    // Skip Select interaction — email format error shows regardless of department selection
    // Submit form
    fireEvent.click(screen.getByRole('button', { name: 'OK' }));

    await waitFor(() => {
      expect(screen.getByText(/郵箱格式不正確/i)).toBeInTheDocument();
    }, { timeout: 5000 });

    expect(employeeApi.add).not.toHaveBeenCalled();
  });
});
