/**
 * EmployeeList Component Tests
 * Generated by smartadmin-react-crud skill
 */

import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { vi } from 'vitest';
import { Provider } from 'react-redux';
import { configureStore } from '@reduxjs/toolkit';
import { EmployeeList } from '../EmployeeList';
import { employeeApi } from '@/api/system/employee-api';
import userReducer from '@/store/slices/userSlice';

// Mock API
vi.mock('@/api/system/employee-api');

// Create test store
const createTestStore = () => {
  return configureStore({
    reducer: {
      user: userReducer,
    },
    preloadedState: {
      user: {
        token: 'test-token',
        employeeId: '1',
        administratorFlag: true,
        pointsList: [],
        menuTree: [],
      },
    },
  });
};

describe('EmployeeList Component', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should fetch and display employee data on mount', async () => {
    const mockData = {
      success: true,
      data: {
        list: [
          {
            employeeId: 1,
            employeeName: 'John Doe',
            email: 'john@example.com',
            phone: '13800138000',
            departmentId: 1,
            departmentName: '技術部',
            position: 'Senior Developer',
            status: 1,
            createTime: '2026-03-06T10:00:00Z',
            updateTime: '2026-03-06T10:00:00Z',
            deleted: false,
          },
        ],
        total: 1,
        pageNum: 1,
        pageSize: 10,
        pages: 1,
        emptyFlag: false,
      },
    };
    vi.mocked(employeeApi.query).mockResolvedValue(mockData);

    const store = createTestStore();
    render(
      <Provider store={store}>
        <EmployeeList />
      </Provider>
    );

    await waitFor(() => {
      expect(screen.getByText('John Doe')).toBeInTheDocument();
      expect(screen.getByText('john@example.com')).toBeInTheDocument();
      expect(screen.getByText('技術部')).toBeInTheDocument();
    });

    expect(employeeApi.query).toHaveBeenCalledWith({
      pageNum: 1,
      pageSize: 10,
      keyword: '',
    });
  });

  it('should handle search keyword input and query', async () => {
    const user = userEvent.setup();
    const store = createTestStore();

    vi.mocked(employeeApi.query).mockResolvedValue({
      success: true,
      data: {
        list: [],
        total: 0,
        pageNum: 1,
        pageSize: 10,
        pages: 0,
        emptyFlag: true,
      },
    });

    render(
      <Provider store={store}>
        <EmployeeList />
      </Provider>
    );

    const searchInput = screen.getByPlaceholderText('請輸入搜索關鍵字');
    await user.type(searchInput, 'test');

    const queryButton = screen.getByText('查詢');
    await user.click(queryButton);

    await waitFor(() => {
      expect(employeeApi.query).toHaveBeenCalledWith(
        expect.objectContaining({ keyword: 'test' })
      );
    });
  });

  it('should open form modal when add button clicked', async () => {
    const user = userEvent.setup();
    const store = createTestStore();

    vi.mocked(employeeApi.query).mockResolvedValue({
      success: true,
      data: {
        list: [],
        total: 0,
        pageNum: 1,
        pageSize: 10,
        pages: 0,
        emptyFlag: true,
      },
    });

    render(
      <Provider store={store}>
        <EmployeeList />
      </Provider>
    );

    const addButton = screen.getByText('新增員工');
    await user.click(addButton);

    await waitFor(() => {
      expect(screen.getAllByText('新增員工').length).toBeGreaterThan(1);
    });
  });

  it('should call delete API and refresh data when delete confirmed', async () => {
    const mockQueryData = {
      success: true,
      data: {
        list: [
          {
            employeeId: 1,
            employeeName: 'John Doe',
            email: 'john@example.com',
            phone: '13800138000',
            departmentId: 1,
            departmentName: '技術部',
            position: 'Developer',
            status: 1,
            createTime: '2026-03-06T10:00:00Z',
            updateTime: '2026-03-06T10:00:00Z',
            deleted: false,
          },
        ],
        total: 1,
        pageNum: 1,
        pageSize: 10,
        pages: 1,
        emptyFlag: false,
      },
    };
    vi.mocked(employeeApi.query).mockResolvedValue(mockQueryData);
    vi.mocked(employeeApi.delete).mockResolvedValue({ success: true });

    const user = userEvent.setup();
    const store = createTestStore();

    render(
      <Provider store={store}>
        <EmployeeList />
      </Provider>
    );

    await waitFor(() => {
      expect(screen.getByText('John Doe')).toBeInTheDocument();
    });

    const deleteButtons = screen.getAllByText('刪除');
    await user.click(deleteButtons[0]);

    await waitFor(() => {
      const confirmButton = screen.getByText('確定');
      return user.click(confirmButton);
    });

    await waitFor(() => {
      expect(employeeApi.delete).toHaveBeenCalledWith(1);
    });
  });

  it('should handle pagination change', async () => {
    const store = createTestStore();
    const user = userEvent.setup();

    vi.mocked(employeeApi.query).mockResolvedValue({
      success: true,
      data: {
        list: [],
        total: 100,
        pageNum: 1,
        pageSize: 10,
        pages: 10,
        emptyFlag: false,
      },
    });

    render(
      <Provider store={store}>
        <EmployeeList />
      </Provider>
    );

    // Wait for initial render
    await waitFor(() => {
      expect(employeeApi.query).toHaveBeenCalled();
    });

    // Clear mock to test pagination
    vi.mocked(employeeApi.query).mockClear();

    // Find page 2 button and click it
    const page2Button = screen.getByText('2');
    await user.click(page2Button);

    await waitFor(() => {
      expect(employeeApi.query).toHaveBeenCalledWith(
        expect.objectContaining({ pageNum: 2 })
      );
    });
  });
});
