-- V003: Create Payment Module Tables
-- Author: iGaming Team
-- Date: 2026-03-19
-- Description: Payment order table for unified deposit/withdrawal processing

-- ============================================================================
-- Table: t_payment_order
-- Description: Unified payment order table for deposits and withdrawals
-- ============================================================================

CREATE TABLE t_payment_order (
    -- Primary Key
    payment_order_id    BIGSERIAL PRIMARY KEY,

    -- Multi-Tenant Isolation
    tenant_id           BIGINT NOT NULL,

    -- Order Information
    order_no            VARCHAR(50) NOT NULL,         -- Unique order number (generated by system)
    player_id           BIGINT NOT NULL,              -- Foreign key to t_player
    wallet_id           BIGINT NOT NULL,              -- Foreign key to t_wallet

    -- Order Type & Amount
    order_type          INTEGER NOT NULL,             -- PaymentOrderTypeEnum: 1=DEPOSIT, 2=WITHDRAWAL
    amount              NUMERIC(19,4) NOT NULL,       -- Order amount with 0.0001 precision
    currency_code       VARCHAR(3) NOT NULL,          -- ISO 4217: USD, EUR, etc.

    -- Order Status
    status              INTEGER NOT NULL,             -- PaymentOrderStatusEnum: 1=PENDING, 2=PROCESSING, 3=SUCCESS, etc.

    -- PSP (Payment Service Provider) Information
    psp_code            VARCHAR(50),                  -- PSP identifier code
    psp_transaction_id  VARCHAR(100),                 -- PSP transaction reference ID
    redirect_url        TEXT,                         -- PSP redirect URL for user
    callback_payload    TEXT,                         -- PSP callback data (JSON)

    -- Idempotency & Reference
    request_id          VARCHAR(100) NOT NULL,        -- Unique request ID for idempotency
    description         TEXT,                         -- Order description

    -- Reconciliation
    reconciliation_status INTEGER,                    -- ReconciliationStatusEnum: 1=PENDING, 2=VERIFIED, etc.

    -- Optimistic Lock & Soft Delete
    version             INTEGER NOT NULL DEFAULT 0,
    deleted             BOOLEAN NOT NULL DEFAULT FALSE,

    -- SmartAdmin Base Entity Fields
    create_time         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Consistency Check Constraint
    CONSTRAINT chk_payment_order_amount_positive CHECK (amount > 0)
);

-- ============================================================================
-- Indexes for t_payment_order
-- ============================================================================

-- Unique constraint: One order per order_no (business primary key)
CREATE UNIQUE INDEX uk_payment_order_order_no
    ON t_payment_order (order_no)
    WHERE deleted = false;

-- Unique constraint: One order per request_id (idempotency)
CREATE UNIQUE INDEX uk_payment_order_request_id
    ON t_payment_order (tenant_id, request_id)
    WHERE deleted = false;

-- Player order lookup index (for player order history)
CREATE INDEX idx_payment_order_player
    ON t_payment_order (tenant_id, player_id, create_time DESC)
    WHERE deleted = false;

-- Wallet order lookup index (for wallet reconciliation)
CREATE INDEX idx_payment_order_wallet
    ON t_payment_order (wallet_id, create_time DESC)
    WHERE deleted = false;

-- Order type query index (for deposit/withdrawal statistics)
CREATE INDEX idx_payment_order_type_status
    ON t_payment_order (tenant_id, order_type, status, create_time DESC)
    WHERE deleted = false;

-- PSP transaction lookup index (for callback processing)
CREATE INDEX idx_payment_order_psp_transaction
    ON t_payment_order (psp_code, psp_transaction_id)
    WHERE deleted = false AND psp_transaction_id IS NOT NULL;

-- Reconciliation status index (for reconciliation jobs)
CREATE INDEX idx_payment_order_reconciliation
    ON t_payment_order (tenant_id, reconciliation_status, create_time DESC)
    WHERE deleted = false AND reconciliation_status IS NOT NULL;

-- Tenant isolation index
CREATE INDEX idx_payment_order_tenant
    ON t_payment_order (tenant_id)
    WHERE deleted = false;

-- ============================================================================
-- Foreign Key Constraints
-- ============================================================================

-- Foreign key: t_payment_order.player_id -> t_player.player_id
ALTER TABLE t_payment_order
    ADD CONSTRAINT fk_payment_order_player
    FOREIGN KEY (player_id)
    REFERENCES t_player (player_id)
    ON DELETE RESTRICT;  -- Cannot delete player if payment orders exist

-- Foreign key: t_payment_order.wallet_id -> t_wallet.wallet_id
ALTER TABLE t_payment_order
    ADD CONSTRAINT fk_payment_order_wallet
    FOREIGN KEY (wallet_id)
    REFERENCES t_wallet (wallet_id)
    ON DELETE RESTRICT;  -- Cannot delete wallet if payment orders exist

-- ============================================================================
-- Table Comments
-- ============================================================================

COMMENT ON TABLE t_payment_order IS
'Unified payment order table for deposits and withdrawals. Supports idempotency via request_id UNIQUE constraint. Integrates with PSP (Payment Service Provider) via psp_code and psp_transaction_id. Reconciliation status tracks post-processing verification.';

-- ============================================================================
-- Column Comments for t_payment_order
-- ============================================================================

COMMENT ON COLUMN t_payment_order.payment_order_id IS 'Payment order unique identifier (auto-increment)';
COMMENT ON COLUMN t_payment_order.tenant_id IS 'Tenant ID for multi-tenant isolation';
COMMENT ON COLUMN t_payment_order.order_no IS 'Unique order number (business primary key, system-generated)';
COMMENT ON COLUMN t_payment_order.player_id IS 'Player ID (foreign key to t_player)';
COMMENT ON COLUMN t_payment_order.wallet_id IS 'Wallet ID (foreign key to t_wallet)';
COMMENT ON COLUMN t_payment_order.order_type IS 'Order type: 1=DEPOSIT, 2=WITHDRAWAL (see PaymentOrderTypeEnum)';
COMMENT ON COLUMN t_payment_order.amount IS 'Order amount (DECIMAL(19,4) for 0.0001 precision)';
COMMENT ON COLUMN t_payment_order.currency_code IS 'ISO 4217 currency code (USD, EUR, CNY, etc.)';
COMMENT ON COLUMN t_payment_order.status IS 'Order status: 1=PENDING, 2=PROCESSING, 3=SUCCESS, 4=FAILED, 5=REJECTED, 6=REFUNDED, 7=CANCELLED (see PaymentOrderStatusEnum)';
COMMENT ON COLUMN t_payment_order.psp_code IS 'Payment Service Provider identifier code (e.g., STRIPE, PAYPAL, PAGSMILE)';
COMMENT ON COLUMN t_payment_order.psp_transaction_id IS 'PSP transaction reference ID (for reconciliation and callbacks)';
COMMENT ON COLUMN t_payment_order.redirect_url IS 'PSP redirect URL for user to complete payment (for redirected payment flows)';
COMMENT ON COLUMN t_payment_order.callback_payload IS 'PSP callback data (JSON format, for audit trail)';
COMMENT ON COLUMN t_payment_order.request_id IS 'Unique request ID for idempotency (prevents duplicate submissions)';
COMMENT ON COLUMN t_payment_order.description IS 'Order description (for customer service and audit purposes)';
COMMENT ON COLUMN t_payment_order.reconciliation_status IS 'Reconciliation status: 1=PENDING, 2=VERIFIED, 3=MISMATCH, 4=COMPENSATED, 5=RECONCILED (see ReconciliationStatusEnum)';
COMMENT ON COLUMN t_payment_order.version IS 'Optimistic lock version for concurrent update protection';
COMMENT ON COLUMN t_payment_order.deleted IS 'Soft delete flag';
COMMENT ON COLUMN t_payment_order.create_time IS 'Order creation timestamp';
COMMENT ON COLUMN t_payment_order.update_time IS 'Last update timestamp';
